### ISSUE TITLE
Error in the README example (and others in documentation)

### ISSUE THREAD

**Issue by martha-thomae** [craigsapp/humlib#41]
I am pretty new to C++, but I think there are a few errors in the README example and the other examples in the [humlib page](https://humlib.humdrum.org/). I had to make a few changes to make the example work. Here is the final, corrected code:

```c++
#include "humlib.h"

using namespace std;
using namespace hum;

void printNoteInformation(HumdrumFile& infile, int line, int field, int tpq) {
   int starttime = infile[line].getDurationFromStart(tpq).getInteger();
   int duration  = infile.token(line, field)->getDuration(tpq).getInteger();
   cout << Convert::kernToSciPitch(*infile.token(line, field))
        << '\t' << infile.token(line, field)->getTrackString()
        << '\t' << starttime << '\t' << duration << endl;
}

int main(int argc, char** argv) {
   if (argc != 2) {
      return 1;
   }
   HumdrumFile infile;
   if (!infile.read(argv[1])) {
      return 1;
   }
   int tpq = infile.tpq();
   cout << "TPQ: " << tpq << endl;
   cout << "PITCH\tTRACK\tSTART\tDURATION" << endl;

   for (int i=0; i<infile.getLineCount(); i++) {
      if (!infile[i].isData()) {
         continue;
      }
      for (int j=0; j<infile[i].getTokenCount(); j++) {
         if (infile.token(i, j)->isNull()) {
            continue;
         }
         if (infile.token(i, j)->isDataType("kern")) {
            printNoteInformation(infile, i, j, tpq);
         }
      }
   }
   return 0;
}
```
The changes compared to the original can be seen in the following screenshot (original is in the left side, corrected version is in the right side):
![Screen Shot 2021-01-16 at 4 19 10 PM](https://user-images.githubusercontent.com/13948831/104823249-d4581800-5816-11eb-9465-c8926a381e7f.png)

**Comment by craigsapp** [comment]
Thanks!  Looking at the README, it is basically from 2015 and from before I created https://humlib.humdrum.org for documentation (that documentation may not be complete because I am lazy and read the source code as documentation for myself :-), so complain when anything is missing or more explanation is needed.

 I vaguely remember now that I changed the return value of `HumdrumFile::token` from  `HumdrumToken&` to `HumdrumToken*`.   The `HumdrumToken&` (reference variable) method was quite confusing and complicated to work with probably, so I switched to pointers.

Fixed with commit https://github.com/craigsapp/humlib/commit/7aca7d5dd13fe6b297d1dc49267fbedb214b8df6

**Comment by craigsapp** [comment]
I also fixed the example program to be able to handle rests and chords.  I also adjusted the style to make it somewhat more readable without cluttering it with comments.  The `HTp` data type is a typedef for `HumdrumToken*`.  If you ever see `HLp` that is a typedef for `HumdrumLine*` (used less often).

There is a limitation with chords in the example program: all notes in chords have to be either tied or not tied as the same time.   That is usually true in real music, but not always.
