### ISSUE TITLE
Be more graceful when no data terminators are given in data

### ISSUE THREAD

**Issue by craigsapp** [craigsapp/humlib#54]
See https://github.com/rism-digital/verovio/issues/3142

**Comment by malcolmsailor** [comment]
Thanks for opening this issue.

Yes, you are correct, I was using verovio on the command line. I was just running `verovio temp.krn` and getting a segmentation fault.

For reference, here are some factors that made it hard for me to notice that the issue was that the file was missing the terminal `*-` tokens:

1. I had many other files, which I've realized are also missing the `*-` tokens, on which verovio ran just fine.
2. If I deleted the last measure of the file as I sent it to you as in [temp2.krn.zip](https://github.com/craigsapp/humlib/files/10185123/temp2.krn.zip), verovio ran just fine. (In fact I went through the file deleting measures one by one to try to locate the problem.)
3. If I deleted the `autobeam` filter, verovio ran just fine.

Thus, while the root cause was the missing terminators, it was hard for me to locate this because the incorrect syntax didn't directly cause the problem (or raise a transparent error or warning message). Instead, the error was caused by the combination of all three of
1. the incorrect syntax (missing terminators)
2. something about the particular sequence of measures in that file
3. the autobeam filter

You might be way ahead of me but I suspect the most helpful solution would be just to print to the terminal a warning whenever data terminators are missing. In fact, there *is* a warning: `Should not get here in analyzeSpineStrands()`. However I was seeing this for all of my files (because they were all missing terminators) but only some of them were crashing (only this one, as far as I knew), so I didn't realize that it was the cause, nor was it transparent to me how to address the warning. A message like `Missing data terminator: all spines should end with '*-'` would be much more helpful for non-experts such as me.

Finally, concerning [https://verovio.humdrum.org/](https://verovio.humdrum.org/), where there is a warning printed concerning the missing terminators, I'm trying to figure out why I didn't see that. I think the reason must be  because in my actual file, there is a good deal more metadata after the autobeam filter, and so the actual warning is only down at the bottom, where I must have missed it:

<img width="392" alt="Screen Shot 2022-12-08 at 7 10 42 AM" src="https://user-images.githubusercontent.com/28103673/206443393-1f0b4f0f-850b-449a-b22d-7ff1993243d0.png">

**Comment by craigsapp** [comment]
Commit https://github.com/craigsapp/humlib/commit/41ad7916061f9b6f5760f852b85117f96cab36e8 fixes the crash that can happen when autobeam is used on an unterminated spine. 

In addition a less cryptic error message will be displayed on the command-line or in a web browser console about the missing terminator.

>  However I was seeing this for all of my files

I think I told you about this a few years ago 😉.   VHV does not (or should not) care about missing terminators, but they can cause unpredictable behavior for Humdrum tools (such as with autobeam) since the input data is presumed to be valid.   There is the `humdrum` tool from the original Humdrum Toolkit which checks for basic Humdrum syntax problems, which catches this error on the command-line:

```bash
humdrum file.krn
```

which has a report like this for missing terminators:

```
humdrum: ERROR 14: All spines have not been properly terminated
                   in line 3, file test.krn.
```

In VHV I want to see the music as it is being typed so the terminator requirement was downgraded to a warning.  

VHV has a javascript clone of the `humdrum` tool, and it will mark syntax errors with a red box in the gutter.   The only exception is the lack of terminator, which was converted to a warning rather than an error.  The Humdrum text is checked for errors, and if there are any, the notation is highlighted in pink to indicate that the Humdrum data was not processed.
